### ISSUE TITLE
MSVC 22: 'Bit' Undefined in Codec_Choose.c Line 222  with HAVE_AVX512 defined

### ISSUE THREAD

**Issue by micthom** [aklomp/base64#147]
I am getting the following error when compiling with AVX512 support enabled. I have tested this under an i9-10920X and Intel Xeon 8272CL processor. If I disable AVX512 the project will compile. 

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C4013	'bit' undefined; assuming extern returning int	base64	C:\source\libs\base64\lib\codec_choose.c	222

**Comment by aklomp** [comment]
Fixed by #145.
