### ISSUE TITLE
Is there is a plan to support RFC 2045?

### ISSUE THREAD

**Issue by zhanglistar** [aklomp/base64#148]
Hi, @aklomp Thanks for your great work on base64 RFC4648! While RFC 2045 is used in Apache Spark, do you have plan to support RFC 2045? Thanks in advance.

**Comment by aklomp** [comment]
Hi, I'm not sure what you mean exactly by RFC 2045 support, can you explain?

If this is about adding support for e-mail features, I'm afraid I don't have plans in that direction. This library is just an encoder/decoder for raw base64 streams.

**Comment by zhanglistar** [comment]
Yes it's about e-mail features.
