### ISSUE TITLE
[Question] Library is supported?

### ISSUE THREAD

**Issue by ikrivosheev** [aklomp/base64#49]
Subject... Or maybe there are alternatives?

**Comment by aklomp** [comment]
If it answers your question: this library is currently not under active development. I've moved on to other projects and interests in my spare time. Life's short and there's so much to do!

In my opinion, the project has met the goals which it set out to achieve, which is to be a small and fast library without too much fluff. It's more or less feature complete, though it's of course not perfect. I have some vague plans to do some cleanups, but probably not in the near future.

As for support, this library never really had any. It's licensed under the 2-clause BSD license, which means that the library is provided as-is. There may be alternatives which offer more support or community in that regard. If you search github for base64, you'll find many different projects with varying goals.

**Comment by ikrivosheev** [comment]
Ok, thank you.
