### ISSUE TITLE
Cleanup round (no functional inpact) before releasing v0.4.0

### ISSUE THREAD

**Issue by aklomp** [aklomp/base64#55]
I would like to release a new library version (v0.4.0) which puts a tag on the code that everyone has been using for the last few years. This will make room to introduce some breaking changes from here on forward.

However, before we can release, the code is in need of a cleanup round. The codebase has accumulated a lot of patches from various contributors, in various different styles. This has led to some inconsistencies with how things are done, as well as diminished the quality of comments, and accumulated dead code.

Objective: push a set of commits which fix many of these issues, *without introducing any functional changes*. The library *code*, as seen by the compiler, must remain unchanged from what it is now, to avoid regressions for anyone switching to this new version.

- Fix some trivial whitespace issues (wrong indent, trailing whitespace, etc).
- Reword some comments for clarity.
- Split some monolithic code files into smaller parts, to conform to the general style.
- Uniform style for function declarations, bodies of `if` statements, etc.
- Remove dead code.
- Remove the now unnecessary `CMPGT` macros and friends.

**Comment by aklomp** [comment]
Yes, I intend to do a new release once everyone is happy with the `cmake` stuff. The reason is that I might want to make some API changes, like remove the `avx` codec (which is identical to `ssse3` right now) and rethink the runtime feature detection a bit.

**Comment by BurningEnlightenment** [comment]
Would you mind creating an [meta-issue] (and perhaps a milestone) to track the open work?

[meta-issue]: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists
