### ISSUE TITLE
_MSC_VER's #define BASE64_HTOBE64 codepath in env.h should #include <intrin.h>

### ISSUE THREAD

**Issue by mgambrell** [aklomp/base64#68]
without `#include <intrin.h>`, `_byteswap_uint64` is undefined at point of use and assumed due to C sucking to be returning an int.. an int that's 32bits. this makes the result be garbled (for future searchers, it makes it 32bits sign extended into `src`).

**Comment by aklomp** [comment]
Thanks for the report. Good catch, what a crappy bug. Unfortunately the CI doesn't build the library for Windows yet due to missing Cmake support, or this would have been caught by the automated tests. I pushed an `issue68` branch, can you confirm that it fixes the bug?

**Comment by mgambrell** [comment]
works for me, looks sensible by inspection.

**Comment by aklomp** [comment]
Thanks, merged.
