### ISSUE TITLE
How to build in xcode?

### ISSUE THREAD

**Issue by woniupapa** [aklomp/base64#72]
I want to use it in ios project. how to build it in xcode? help!!!

**Comment by aklomp** [comment]
Sorry, I have no experience with iOS or xcode. The library is a relatively straightforward C project, so I don't think it should be too hard to get it running. Maybe you can find a fork of this project which builds it for xcode.

**Comment by aklomp** [comment]
This library now integrates with CMake, so it should be possible to use it like any other library that uses CMake.
