### ISSUE TITLE
decode size_t failed

### ISSUE THREAD

**Issue by lihongyi1234** [aklomp/base64#73]
hello, I test the fast64 decode, it indeed faster than other code, but i counter a problem when using function int base64_decode( const char*src, size_t srclen, char *out, size_t	*outlen, int flags) ; it's unknow about out's size ,it easy to decode failed when size is small, how can i solve it

**Comment by aklomp** [comment]
The output buffer should be at least 3/4 the size of the input buffer, because every four Base64 bytes are turned into three regular bytes. The user is responsible for allocating a large enough buffer using this rule of thumb.
