### ISSUE TITLE
CI: GitHub Actions: build and test on different architectures

### ISSUE THREAD

**Issue by aklomp** [aklomp/base64#83]
The old Travis CI config compiled and tested the code on various architectures: `arm32`, `arm64`, `ppc64be`, `ppc64le` and `s390`. We can partly replicate this with GitHub Actions by using the [`uraimo/run-on-arch-action`](https://github.com/uraimo/run-on-arch-action). Update the CI config to run and test the library on various architectures.

Unfortunately, `uraimo/run-on-arch-action` does not support a big-endian architecture (yet?). It would be nice if we could find a way to include such an architecture in the test matrix.

An example of a project that uses this CI setup is [aklomp/vec](https://github.com/aklomp/vec).

**Comment by mayeut** [comment]
> Unfortunately, uraimo/run-on-arch-action does not support a big-endian architecture (yet?). It would be nice if we could find a way to include such an architecture in the test matrix.

s390x is big-endian.
